### ISSUE TITLE
Sharing project code quality feedback [for @kuanming3] - Round 2

### ISSUE THREAD

**Issue by nus-se-script** [Kuanming3/duke#1]
@kuanming3 We did an automated analysis of your code to detect potential areas to improve the code quality. We are sharing the results below, to help you improve the project code further.

IMPORTANT: Note that the script looked for **just a few easy-to-detect problems only**, and **at-most three example are given** i.e., there can be other areas/places to improve.

### Aspect: Tab Usage

No easy-to-detect issues :+1: 

### Aspect: Naming boolean variables/methods

No easy-to-detect issues :+1: 

### Aspect: Brace Style

No easy-to-detect issues :+1: 

### Aspect: Package Name Style

No easy-to-detect issues :+1: 

### Aspect: Class Name Style

No easy-to-detect issues :+1: 

### Aspect: Dead Code

No easy-to-detect issues :+1: 

### Aspect: Method Length

No easy-to-detect issues :+1: 

### Aspect: Class size

No easy-to-detect issues :+1: 

### Aspect: Header Comments

Example from [`src/main/java/duke/TaskList.java` lines `17-19`](https://github.com/kuanming3/duke/blob/d644c5f84e560ab6d4d3127e4a9a9d198d761ee0/src/main/java/duke/TaskList.java#L17..L19):

```java

    /**
     * Find task with keyword exist in task description
     */

```

Example from [`src/main/java/duke/TaskList.java` lines `35-37`](https://github.com/kuanming3/duke/blob/d644c5f84e560ab6d4d3127e4a9a9d198d761ee0/src/main/java/duke/TaskList.java#L35..L37):

```java

    /**
     * Print all filtered tasks
     */

```

Example from [`src/main/java/duke/TaskList.java` lines `45-47`](https://github.com/kuanming3/duke/blob/d644c5f84e560ab6d4d3127e4a9a9d198d761ee0/src/main/java/duke/TaskList.java#L45..L47):

```java

    /**
     * Print all tasks
     */

``` 

**Suggestion:** Ensure method/class header comments follow the format specified in the coding standard, in particular, the phrasing of the overview statement.

### Aspect: Binary files in repo

No easy-to-detect issues :+1: 

:information_source: The bot account used to post this issue is un-manned. **Do not reply to this post** (as those replies will not be read). Instead, contact `tic2002@comp.nus.edu.sg` if you want to follow up on this post.

**Comment by Kuanming3** [comment]
Fixed
